language: android

jdk:
  - oraclejdk8


android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        openssl aes-256-cbc -K $encrypted_3327ea27a2f5_key -iv $encrypted_3327ea27a2f5_iv -in Bin.jks.enc -out Bin.jks -d;
        ./gradlew assembleRelease --stacktrace;
        rm Bin.jks;
    else
        ./gradlew assembleDebug  --stacktrace;
    fi


before_deploy:
  - cp app/build/outputs/apk/release/*-release.apk ~
  - export APK_PATH=$(readlink -f ~/*-release.apk)
  - echo $APK_PATH

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $APK_PATH
  overwrite: true
  on:
    tags: true

after_deploy:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem install fir-cli
  - fir p $APK_PATH -T $FIR_TOKEN -c "$(git log -1 $TRAVIS_TAG)"
